fixesss

diff --git a/pkgadd b/pkgadd
--- a/pkgadd
+++ b/pkgadd
@@ -36,11 +36,11 @@ msg2() {
 }
 
 msgerr() {
-	echo "==> ERROR: $1"
+	echo "==> ERROR: $1" >&2
 }
 
 msgwarn() {
-	echo "==> WARNING: $1"
+	echo "==> WARNING: $1" >&2
 }
 
 help() {
@@ -140,7 +140,7 @@ LOCK_FILE="$SCRATCHPKG_DIR/spkg.lock"
 }
 
 [ -d "$ROOT_DIR/$INDEX_DIR" ] || {
-	msgerr "Package's database directory not exist! ($ROOT_DIR/$INDEX_DIR)"
+	msgerr "Package's database directory not exist: $ROOT_DIR/$INDEX_DIR"
 	ret 1
 }
 
diff --git a/pkgbuild b/pkgbuild
--- a/pkgbuild
+++ b/pkgbuild
@@ -27,46 +27,59 @@ msg2() {
 }
 
 msgerr() {
-	echo "==> ERROR: $1"
+	echo "==> ERROR: $1" >&2
 }
 
 msgwarn() {
-	echo "==> WARNING: $1"
+	echo "==> WARNING: $1" >&2
 }
 
 updatemdsum() {
-	msg "Generating .checksums..."
-	generatemdsum > .checksums
-}
-
-generatemdsum() {	
-	if [ -z "$source" ]; then
-		echo SKIP
-		return 0
-	fi
-	
-	for src in $source; do
-		if echo $src | grep -qE "::(ftp|http|https)://"; then
-			FILENAME=$SOURCE_DIR/$(echo $src | awk -F '::' '{print $1}')
-		elif echo $src | grep -qE "(ftp|http|https)://"; then
-			FILENAME=$SOURCE_DIR/$(basename $src)
-		else
-			FILENAME=$src
+	for s in $(getsourcelist); do
+		if [ ! -f $s ]; then
+			msgerr "Source file '$s' not found."
+			err=1
 		fi
-		needupdatechecksum="$needupdatechecksum $FILENAME"
 	done
-	
-	md5sum $needupdatechecksum | sed -e 's|  .*/|  |' | sort -k 2
+	[ "$err" = 1 ] && abort 1
+	generatemdsum > .checksums
+	msg "Checksums updated."
 }
 
-checkmdsum() {	
+getsourcelist() {
+	for s in $source; do
+		if echo $s | grep -qE "::(ftp|http|https)://"; then
+			FILENAME=$SOURCE_DIR/$(echo $s | awk -F '::' '{print $1}')
+		elif echo $s | grep -qE "(ftp|http|https)://"; then
+			FILENAME=$SOURCE_DIR/$(basename $s)
+		else
+			FILENAME=$PWD/$s
+		fi
+			echo $FILENAME
+	done
+}
+
+generatemdsum() {
+	for s in $(getsourcelist); do
+		if [ -f $s ]; then
+			needupdatechecksum="$needupdatechecksum $s"
+		fi
+	done
+	if [ "$needupdatechecksum" ]; then
+		md5sum $needupdatechecksum | sed -e 's|  .*/|  |' | sort -k 2
+	else
+		echo SKIP
+	fi
+}
+
+checkmdsum() {
+	[ "$CHECK_MDSUM" = 0 ] || [ "$IGNORE_MDSUM" = yes ] && return 0
 	TMPCHECKSUM=$WORK_DIR/checksumstmp.$$
 	ORICHECKSUM=$WORK_DIR/checksumsori.$$
 	DIFCHECKSUM=$WORK_DIR/checksumsdiff.$$
 	
 	if [ ! -f .checksums ]; then
-		msg "Generating .checksums..."
-		generatemdsum > .checksums
+		updatemdsum
 	else
 		msg "Checking checksums..."
 		generatemdsum > "$TMPCHECKSUM"
@@ -134,8 +147,6 @@ download_src() {
 }
 
 prepare_src() {	
-	[ "$IGNORE_MDSUM" -o "$CHECK_MDSUM" = 0 ] || checkmdsum
-	
 	SRC=$WORK_DIR/$name/src
 	PKG=$WORK_DIR/$name/pkg
 	
@@ -160,6 +171,11 @@ prepare_src() {
 					break
 				fi
 			done
+			if [ ! -f $FILENAME ]; then
+				msgerr "File source '$FILENAME' not found."
+				err=1
+				continue
+			fi
 			if [ "$FILENAME" != "$FILE" ] && [ "$nxt" != 1 ]; then
 				case $FILENAME in
 					*.tar|*.tar.gz|*.tar.Z|*.tgz|*.tar.bz2|*.tbz2|*.tar.xz|*.txz|*.tar.lzma|*.zip|*.rpm)
@@ -171,7 +187,7 @@ prepare_src() {
 						MODE="Unpacking" ;;
 					*)
 						COMMAND="cp $FILENAME $SRC"
-						MODE="Preparing" ;;				
+						MODE="Preparing" ;;
 				esac
 				msg "$MODE '$(basename $FILENAME)'..."
 				$COMMAND || {
@@ -216,8 +232,30 @@ run_build() {
 	cd - >/dev/null
 }
 
+pkglint() {
+	linterror=0
+	
+	# cant package empty PKG
+	if [ ! "$(find $PKG/* -maxdepth 1 -type d 2>/dev/null)" ]; then
+		msgerr "PKG is empty."
+		abort 1
+	fi
+	
+	# check for backup file
+	for f in $backup; do
+		if [ ! -f $PKG/$f ]; then
+			msgerr "Backup file '$f' not exist in PKG!"
+			linterror=1
+		fi
+	done
+	
+	if [ "$linterror" = 1 ]; then
+		abort 1
+	fi
+}
+
 removeemptydirs() {	
-	find . -type d -empty -delete	
+	find . -type d -empty -delete
 }
 
 removelibtool() {	
@@ -287,12 +325,7 @@ compressinfomanpages() {
 
 backupconf() {
 	for FILE in $backup; do
-		if [ ! -f $FILE ]; then
-			msgerr "File '$FILE' not exist!"
-			abort 1
-		else
-			mv $FILE $FILE.spkgnew
-		fi
+		mv $FILE $FILE.spkgnew
 	done
 }
 
@@ -316,6 +349,9 @@ removelocales() {
 }
 
 packaging() {
+	# lint $PKG before packaging
+	pkglint
+	
 	for FILE in $INCLUDEINPKG; do
 		if [ -f $FILE ]; then
 			install -m644 $FILE $PKG/.pkg$FILE
@@ -332,9 +368,6 @@ packaging() {
 	[ -d usr/share/fonts ] && {
 		find usr/share/fonts \( -name fonts.dir -o -name fonts.scale \) -delete
 	}
-	
-	# remove pseudo directories
-	#rm -fr dev sys proc run tmp
 	
 	[ "$KEEP_EMPTYDIR" = 0 ] && removeemptydirs
 	[ "$KEEP_LIBTOOL" = 0 ]  && removelibtool
@@ -380,11 +413,11 @@ generate_pkgfiles() {
 		excludefile="$excludefile --exclude=.pkg$i"
 	done
 	
-	msg "Generating .pkgfiles..."
 	tar -tvf "$PACKAGE_DIR/$PKGNAME" $excludefile \
 	| awk '{$3=$4=$5=""; print $0}' \
 	| sed "s,lib/modules/$(uname -r),lib/modules/<kernelversion>,g" \
 	| sort -k 3 > .pkgfiles
+	msg "Pkgfiles updated."
 }
 
 cleanup() {
@@ -579,13 +612,13 @@ extract_opts() {
 	echo $opts
 }
 
-main() {	
+main() {
 	parse_opts $(extract_opts "$@")
 	
 	if [ -f "$PKGBUILD_CONF" ]; then
 		. "$PKGBUILD_CONF"
 	else
-		msgerr "Config file not found ('$PKGBUILD_CONF')"
+		msgerr "Config file not found: $PKGBUILD_CONF"
 		exit 1
 	fi
 	
@@ -603,7 +636,7 @@ main() {
 	
 	if [ -f "$PKGBUILD_BSCRIPT" ]; then
 		description=$(grep "^# description[[:blank:]]*:" $PKGBUILD_BSCRIPT | sed 's/^# description[[:blank:]]*:[[:blank:]]*//')
-		. ./$PKGBUILD_BSCRIPT	
+		. ./$PKGBUILD_BSCRIPT
 	else
 		msgerr "'$PKGBUILD_BSCRIPT' file not found."
 		exit 1
@@ -631,14 +664,12 @@ main() {
 	
 	# extract source only
 	[ "$EXTRACT_ONLY" ] && {
-		download_src
 		prepare_src
 		exit 0
 	}
 	
 	# update md5sum
 	[ "$UPDATE_MDSUM" ] && {
-		download_src
 		updatemdsum
 		exit 0
 	}
@@ -673,6 +704,7 @@ main() {
 	else
 		msg "Building '$name-$version-$release'..."
 		download_src
+		checkmdsum
 		prepare_src
 		run_build
 		packaging
diff --git a/pkgdel b/pkgdel
--- a/pkgdel
+++ b/pkgdel
@@ -36,11 +36,11 @@ msg2() {
 }
 
 msgerr() {
-	echo "==> ERROR: $1"
+	echo "==> ERROR: $1" >&2
 }
 
 msgwarn() {
-	echo "==> WARNING: $1"
+	echo "==> WARNING: $1" >&2
 }
 
 help() {	
